### ISSUE TITLE
Publish Pre-Release automatically

### ISSUE THREAD

**Issue by Lemmingh** [yzhang-gh/vscode-markdown#1054]
## Proposal

VS Code 1.63 will allow extensions to have "Pre-Release" (aka "beta", "Insiders"): <https://github.com/microsoft/vscode/issues/15756>

I'd suggest that we publish a Pre-Release **every month**, and roll out a stable one only when receiving positive feedback. The major benefits are:

* We can get more users involved easily to verify significant changes. e.g. #903, #1000

* High-impact problems can be mitigated in time. e.g. #1011

* We won't have to spend unexpectedly long time between releases. e.g. #966

## Tasks

* [ ] Target Node.js 14 and VS Code 1.63. @Lemmingh

  * `vsce` 2.5, which supports the `--pre-release` flag, requires Node.js 14: <https://github.com/microsoft/vscode-vsce/pull/654>

  * VS Code 1.63 or higher is required: <https://github.com/microsoft/vscode/issues/138068>

  This is also quite natural, as things have changed so greatly in the past year that we don't need to stick to our original targeting plan.

* [ ] Revise life cycle management. @yzhang-gh

  Needs Discussion.

* [ ] Update `CHANGELOG` format. @yzhang-gh

  Needs Discussion.

* [ ] Create a protected environment. @yzhang-gh

  * I'd recommend "publish" as its name.

  * It should require approval from @yzhang-gh

  * It should have a wait timer of at least 60 minutes.

  * Please set your VSTS PAT for Marketplace Manage as the `VSCE_PAT` secret there. Note that a VSTS PAT expires in a few months (less than one year). Please remember to update the secret.

  Thank you.

* [ ] Create the CD workflow (`publish.yml`). @Lemmingh

  Given 65f0fa38d0cdf0b8b67cc461ee444d4c91143df9, this should not be difficult.

* [ ] Update docs. @Lemmingh

  Tune the wording of `contributing/diagnostic-data`.

**Comment by yzhang-gh** [comment]
> VS Code 1.63 will allow extensions to have "Pre-Release" (aka "beta", "Insiders"): [microsoft/vscode#15756](https://github.com/microsoft/vscode/issues/15756)

That's interesting. Will do it when I have enough time (one month to go!)

**Comment by Lemmingh** [comment]
Re-target requires refactor; refactor requires re-target; just like an infinite loop. I've been playing with hundreds of compilation errors for three days. 🤐

**Comment by Lemmingh** [comment]
https://code.visualstudio.com/updates/v1_66#_electron-17-update

VS Code 1.66 adopts Node.js 16, while I'm still stuck with webpack. VS Code's docs is so rough about debugging that I have to investigate samples. 😖

**Comment by yzhang-gh** [comment]
That's sad. (I remember that I said I had big trouble with webpack and now you too 😂)

**Comment by Lemmingh** [comment]
Eventually, a new build pipeline seems to work. I've changed 27 files so far. I'll submit a PR tomorrow if everything, excluding running tests locally, looks fine. Sigh.
