### ISSUE TITLE
Task list breaks the decoration of code span

### ISSUE THREAD

**Issue by heartacker** [yzhang-gh/vscode-markdown#1067]
## Problem

![image](https://user-images.githubusercontent.com/1876302/148149291-8c38a422-51d1-4878-b8f9-482fa47c967e.png)

## How to reproduce
打开 markdown all in one

## Configuration

除了这个，其他都没有改动

![image](https://user-images.githubusercontent.com/1876302/148149348-d70f9bea-58f9-4115-8cca-0b4a8736f3a8.png)

## Environment

版本: 1.64.0-insider (system setup)
提交: 990ad4044032b05c0ebf0f67f800c5845baad4c7
日期: 2022-01-04T05:18:15.830Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393

名称: Markdown All in One
ID: yzhang.markdown-all-in-one
说明: All you need to write Markdown (keyboard shortcuts, table of contents, auto preview and more)
版本: 3.4.0
发布者: Yu Zhang
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

**Comment by yzhang-gh** [comment]
想象不出原因。。可以考虑卸载这个插件（重启 VS Code）再重新安装

**Comment by heartacker** [comment]
```markdown
## 11. 问题关键

!!! question
    - [ ] 和 `cpumode0/1` 、`swd` 、`reset` 、 `poweron` 、 `trapping` 、 `clk` 相关pad 都有哪些？
    - [ ] pattern 里面很多无关的pad，导致pattern 很大很宽，不是很好理解和维护，是否可以删减无关的部分
    - [ ] 同上，是否可以直接导出这样的 `tst` 文件而不是糅杂了多有pad的 `tst` 文档？
    - [x] 芯片无任何trapping 下，会进入什么模式?
      - [x] eflash mode
    - [x] 在向 Flash 写入校准值后，为了在 CPU Mode 模式下使用校准值，需要配置 `EN_CALI_CPU_MODEL` 寄存器，地址 `0x40008130` ，要写入什么值？ 【【1.2 将校准值写入Flash】】
      - [x] `A1`
    - [ ] CPU Model 的系统时钟一定要 外灌时钟吗?
    - [x] Cycle长度为35.714ns，即14MHz。外部时钟为28MHz。 这个外部时钟是系统外部时钟还是？ 【【3.2 tst文件时序】】
      - [x] 系统时钟
    - [x] 时钟 CPUMCK 和数据 CPUMD 之间存在延时（一般等于5ns）这个是否需要我们在pattern进行控制，还是说内部已经实现。 【【 AC7840x CPU model 测试应用手册#1 2.4.1 CPU Model写】】
    - [x] 时序图中 `Extern CPUMCLK` 和 `CPUMLK` 都是外灌的吗？ 【【 AC7840x CPU model 测试应用手册#1 2.4.1 CPU Model写】】
      - Extern CPUMCK是芯片外部用于产生CPUMD的工作时钟。CPUMCK在Extern CPUMCK基础上延时得到。
    -  [ ] cpum 一定要使用外部时钟？
    -  [ ] -
```
此内容会导致此问题。
我也搞不懂为啥

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/148154488-1b6e7cad-ee01-4f94-a255-8a15bcd5ae9c.png)

**Comment by yzhang-gh** [comment]
![image](https://user-images.githubusercontent.com/7588612/148155813-ebce7838-5daf-4b3c-965f-20a13570727b.png)

看起来和 <code>\`code`</code> 有关，但是我这里各种主题都正常

**Comment by heartacker** [comment]
现在还需要我提供什么吗？

**Comment by yzhang-gh** [comment]
建议多尝试一下复现的方法，比如把所有插件都禁用，仅仅启用这一个插件，还会有问题吗？

我这不能复现的话也无从修改

**Comment by heartacker** [comment]
我发现我禁用这个插件也可以解决这个问题，
所以我看可能是两者 Markdown All in One 和 Markdown Extended 冲突了。

名称: Markdown Extended
ID: jebbs.markdown-extended
说明: Extended syntaxes to built-in markdown & What you see is what you get exporter.
版本: 1.1.1
发布者: jebbs
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended

**Comment by heartacker** [comment]
感谢，也不知道谁的问题，我先 workaround。 期待修复

**Comment by Lemmingh** [comment]
诶……我在 #966 中分析过这个问题了呀。

**Comment by yzhang-gh** [comment]
> A mysterious bug in decoration of code span in task list.

太不显眼了，并且我也不知道是这个 bug 😂

**Comment by Lemmingh** [comment]
Hum ... 看来，我是在梦里写了后半句。😂

[`markdown-it-task-lists`](https://github.com/revin/markdown-it-task-lists) twists the input, breaking position calculation. We need to have our own implementation; we can name it `markdown-it-task-list`.

**Comment by Lemmingh** [comment]
这个情况跟 <https://github.com/microsoft/vscode/issues/131427> 很接近，也可以算是 #1045 的背景之一。
