### ISSUE TITLE
Add optional strikethrough decoration to checked task list items

### ISSUE THREAD

**Issue by Chrismettal** [yzhang-gh/vscode-markdown#992]
## Proposal

Optionally striking through checked items on task lists in the editor improves readability for bigger lists with multiple checked and unchecked items. 
This extension already enables the strikethrough code decoration like ~~this~~ so another optional regex for `- [x]` striking through the whole line could potentially be easily implemented .

I just briefly tried swapping out the regex in `decorationWorkerRegistry.ts` line 206, but I seem to be missing a general understanding of the extension, since the whole extension just broke, not decorating anything and not reacting to any shortcuts when I did (command not found for keypress [...]) so I sadly can't simulate what it would look like in the editor.

### Current behavior simulated:

- [ ] This is an item with a lot of text and descriptions
- [x] This is an item with a lot of text and descriptions
    - [x] This is an item with a lot of text and descriptions
    - [x] This is an item with a lot of text and descriptions
- [ ] This is an item with a lot of text and descriptions
- [ ] This is an item with a lot of text and descriptions
    - [ ] This is an item with a lot of text and descriptions
    - [x] This is an item with a lot of text and descriptions

### Proposed behavior simulated:

- [ ] This is an item with a lot of text and descriptions
- [x] ~~This is an item with a lot of text and descriptions~~
    - [x] ~~This is an item with a lot of text and descriptions~~
    - [x] ~~This is an item with a lot of text and descriptions~~
- [ ] This is an item with a lot of text and descriptions
- [ ] This is an item with a lot of text and descriptions
    - [ ] This is an item with a lot of text and descriptions
    - [x] ~~This is an item with a lot of text and descriptions~~
